"""Reusable Endfield desktop UI components."""

from .theme import THEME, apply_theme
from .widgets import (
    DetectionBox,
    DeviceStatusRow,
    GainCurve,
    IndustrialField,
    IndustrialIconButton,
    IndustrialSelect,
    IndustrialButton,
    LogConsole,
    MetricCard,
    MetricRail,
    MetricSpec,
    PreviewCanvas,
    SegmentedControl,
    SectionPanel,
    Sidebar,
    StatusBadge,
    TabRail,
    TechSlider,
    TechSwitch,
    TopBar,
)

__all__ = [
    "THEME",
    "DetectionBox",
    "DeviceStatusRow",
    "GainCurve",
    "IndustrialField",
    "IndustrialIconButton",
    "IndustrialSelect",
    "IndustrialButton",
    "LogConsole",
    "MetricCard",
    "MetricRail",
    "MetricSpec",
    "PreviewCanvas",
    "SegmentedControl",
    "SectionPanel",
    "Sidebar",
    "StatusBadge",
    "TabRail",
    "TechSlider",
    "TechSwitch",
    "TopBar",
    "apply_theme",
]
